# !/usr/bin/env python3

#!/usr/bin/env python3

# Main.py file generated by New Project wizard

# Created:   mer. juil. 7 2021
# Processor: RPI4
# Compiler:  Python 3 (Proteus)

# Modules
from goto import *
import time
import var
import pio
import resource
import RPi.GPIO as GPIO

# Peripheral Configuration Code (do not edit)
#---CONFIG_BEGIN---
import cpu
import FileStore
import VFP
import Generic

def peripheral_setup () :
# Peripheral Constructors
pio.cpu=cpu.CPU ()
pio.storage=FileStore.FileStore ()
pio.server=VFP.VfpServer ()
pio.LED1=Generic.LED (pio.GPIO18)
pio.storage.begin ()
pio.server.begin (0)
# Install interrupt handlers

def peripheral_loop () :
pio.server.poll ()

#---CONFIG_END---

# Main function
def main () :
# Setup
    peripheral_setup()

led_pin = 18
GPIO.setmode(GPIO.BOARD)
GPIO.setup(led_pin, GPIO.OUT)

try:
    while True:
        p = GPIO.PWM(18, 100)
        dc = 0
        p.start(dc)
        for x in range(3):
            for i in range(0, 10):
                dc += 10
                p.ChangeDutyCycle(dc)
                time.sleep(1)

            for i in range(0, 10):
                dc -= 10
                p.ChangeDutyCycle(dc)
                time.sleep(1)
        p.stop()     
except KeyboardInterrupt:
    GPIO.cleanup()
   
     
