
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE2_115(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,

	//////////// I2C for HSMC  //////////
	output		          		I2C_SCLK,
	inout 		          		I2C_SDAT,

	//////////// HSMC, HSMC connect to HTG - HSMC to PIO Adaptor //////////
	input 		          		GPIO0_0,
	inout 		          		GPIO0_1,
	inout 		          		GPIO0_10,
	inout 		          		GPIO0_11,
	inout 		          		GPIO0_12,
	inout 		          		GPIO0_13,
	inout 		          		GPIO0_14,
	inout 		          		GPIO0_15,
	inout 		          		GPIO0_16,
	inout 		          		GPIO0_17,
	inout 		          		GPIO0_18,
	inout 		          		GPIO0_19,
	input 		          		GPIO0_2,
	inout 		          		GPIO0_20,
	inout 		          		GPIO0_21,
	inout 		          		GPIO0_22,
	inout 		          		GPIO0_23,
	inout 		          		GPIO0_24,
	inout 		          		GPIO0_25,
	inout 		          		GPIO0_26,
	inout 		          		GPIO0_27,
	inout 		          		GPIO0_28,
	inout 		          		GPIO0_29,
	inout 		          		GPIO0_3,
	inout 		          		GPIO0_30,
	inout 		          		GPIO0_31,
	inout 		          		GPIO0_32,
	inout 		          		GPIO0_33,
	inout 		          		GPIO0_34,
	inout 		          		GPIO0_35,
	inout 		          		GPIO0_4,
	inout 		          		GPIO0_5,
	inout 		          		GPIO0_6,
	inout 		          		GPIO0_7,
	inout 		          		GPIO0_8,
	inout 		          		GPIO0_9,
	input 		          		GPIO1_0,
	inout 		          		GPIO1_1,
	inout 		          		GPIO1_10,
	inout 		          		GPIO1_11,
	inout 		          		GPIO1_12,
	inout 		          		GPIO1_13,
	inout 		          		GPIO1_14,
	inout 		          		GPIO1_15,
	inout 		          		GPIO1_16,
	inout 		          		GPIO1_17,
	inout 		          		GPIO1_18,
	inout 		          		GPIO1_19,
	input 		          		GPIO1_2,
	inout 		          		GPIO1_20,
	inout 		          		GPIO1_21,
	inout 		          		GPIO1_22,
	inout 		          		GPIO1_23,
	inout 		          		GPIO1_24,
	inout 		          		GPIO1_25,
	inout 		          		GPIO1_26,
	inout 		          		GPIO1_27,
	inout 		          		GPIO1_28,
	inout 		          		GPIO1_29,
	inout 		          		GPIO1_3,
	inout 		          		GPIO1_30,
	inout 		          		GPIO1_31,
	inout 		          		GPIO1_32,
	inout 		          		GPIO1_33,
	inout 		          		GPIO1_34,
	inout 		          		GPIO1_35,
	inout 		          		GPIO1_4,
	inout 		          		GPIO1_5,
	inout 		          		GPIO1_6,
	inout 		          		GPIO1_7,
	inout 		          		GPIO1_8,
	inout 		          		GPIO1_9
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



endmodule
